### ISSUE TITLE
Testing AMAZON.FallbackIntent

### ISSUE THREAD

**Issue by markacianfrani** [bespoken/virtual-alexa#109]
Is there any way to test a FallbackIntent? Right now if I utter gibberish, I'll get an error "Unable to match utterance:" 

I'd like to be able to alexa.utter('gibberish') and then assert the response includes my custom FallbackIntent. I can kind of get around this by calling alexa.intent('AMAZON.FallbackIntent') instead.

**Comment by jperata** [comment]
Hi @markacianfrani , calling alexa.intent is the way to do that testing, we are a very good emulator of Alexa, but that is one of our limits compared to what a real AI do to process the voice into Intents, that's one of the reasons the intent method exists, so that you can always test any intent you want either way.
