### ISSUE TITLE
Add reply wrapper, so that emulator can easily be used with assertion frameworks

### ISSUE THREAD

**Issue by jkelvie** [bespoken/virtual-alexa#9]
**Overview**
Create a reply wrapper, which adds convenience methods to the reply payload for testing and other uses.

**Rationale**
We prefer a reply wrapper to building on our own expectations/assertions because there are already many fine assertion frameworks out there. However, making it easy to get data from the JSON response for Alexa is very useful

**Example**
Here is an example of how it might work that uses Jest:
```
reply = ReplyAdapter.tranform(reply); // Adds helper methods
expect(reply.ssml()).toContain("<audio src=\"http://jpk.com"\" />");
expect(reply.plainText()).toBeUndefined();
```

**Useful methods**
```
attr(key) - The session attribute - undefined if it does not exist
card() - The card - an object unto itself with properties for image
plainText() - The plain text reply - if it exists, undefined if not
reprompt() - The reprompt text - if it exists, undefined if not
ssml() - The SSML payload - undefined if it does not exist
```

This is a subset - we can identify more.

Influenced by this issue:
https://github.com/jovotech/jovo-framework-nodejs/issues/39

**Comment by jkelvie** [comment]
@tjbenton - Added this issue after thinking a bit more about your comments on the issue above. Let me know what you think.

**Comment by tjbenton** [comment]
Agreed making a wrapper for the response would be a good idea instead of making your own assertion lib, that way developers can choose their testing framework and not have it chosen for them so to speak. 

I would make the api a little more consistent in terms of `plainText()`, `ssml()`, and `reprompt()`. `plainText()` does indicate that the text will be plain it doesn't indicate if it's the initial prompt, or reprompt. The same goes for the `ssml()` function.

There're 2 options that I can see

The first would be to just make a `payload.plain` getter that will change the `prompt`, `reprompt` and `attr` values to be plain text instead of ssml. These methods would just use an exposed method of `stripSsml`. This is my first option because I think this way improves readability of the tests because it reads more like plain english, and new devs on a project will understand what's happening in the tests.

```js
payload.plain.prompt()
payload.plain.reprompt()
payload.plain.card() // doesn't do anything but would still work
payload.plain.attr(key) // this would remove any ssml that might be saved in attributes 
```

The second would be to pass in a boolean for plain text or ssml. By default the response would be SSML, and if the developer wanted to change it to plain the would just pass in `true`. They could also do `payload.prompt('plain')` since that would be true as well.

```js
payload.prompt(plain = false)
payload.reprompt(plain = false)
payload.card() // no argument needed
payload.attr(key, plain = false) // this would remove any ssml that might be saved in attributes 
```

I would avoid the third way as it just adds extra functions that are doing exactly the same thing just without ssml. I also think this reduces the readability slightly but that's just my personal opinion. It is a viable option.

```js
payload.prompt()
payload.plainPrompt()
payload.reprompt()
payload.plainReprompt()
payload.attr(key)
payload.plainAttr(key)
```


As for the `attr` function, no matter which way it goes I would recommend using the lodash get method for the keys. This way a developer can select something any way they want to like selecting nested items from objects or arrays.

Another useful method would be supporting multiple keys being passed into `attr`, and of course `attrs` as the alias of `attr`. 


```js
// this looks much better than the alternative
payload.plain.attrs('foo', 'bar', 'baz') // { foo: '...', bas: '...', baz: '...' }

// without multiple attr support
// {
//   foo: payload.plain.attrs('foo'),
//   bar: payload.plain.attrs('bar'),
//   baz: payload.plain.attrs('baz'),
// }
```

**Comment by jkelvie** [comment]
I added a first cut of a SkillResponse object - @tjbenton take a look if  you have a chance:
https://github.com/bespoken/virtual-alexa/pull/12/files#diff-e23e6cdf48cbfb6e0aabb6a0380f66a5

**Comment by tjbenton** [comment]
@jkelvie I would recommend defaulting to SSML so you don't have to type `promptSSML`, or `repromptSSML` and you can just type `prompt` and `reprompt`. I would also remove `URL` from `cardSmallImageURL` and `cardLargeImageURL` since the url part is already implied since you're dealing with images.

**Comment by jkelvie** [comment]
Skill response supported added. Latest docs are here:
https://bespoken.github.io/virtual-alexa/api/classes/skillresponse.html
