### ISSUE TITLE
Incorrect type interface for IResponse

### ISSUE THREAD

**Issue by michaelgriscom** [bespoken/virtual-alexa#91]
### Description:
Inside `virtual-alexa\lib\src\core\IResponse.d.ts` the interface is empty:
```
export interface IResponse {
}
```

### Environment:
- Version: 0.6.6
- OS: Windows 10
- Node version: 8.11.3

### Steps To Reproduce
1. Create project using typescript
2. Import IResponse, try to access `response` property on an instance of IResponse

### Expected behavior
Code should compile, `response` property should exist

### Actual behavior
Code fails to compile

### Code example
```javascript
import { IResponse } from "virtual-alexa";
let t: IResponse;
console.log(t.response);
```

**Comment by ig-perez** [comment]
Hello @michaelgriscom, thanks a lot for letting us know and sorry for the inconveniences it might have caused. I'm going to coordinate with the Technical Team, and we’ll get back to you as soon as possible.

**Comment by jkelvie** [comment]
Hi @michaelgriscom IResponse is intended to be empty - typically the concrete type will actually be [SkillResponse](https://bespoken.github.io/virtual-alexa/api/classes/skillresponse.html). 

If you cast the response to this object, you can access any of its properties.
```
await const response = alexa.intend("MyIntent") as SkillResponse;
```

**Comment by michaelgriscom** [comment]
Ah, thanks! Sounds like this isn't a bug then. Wouldn't it be possible to accomplish that through a template parameter though? Having an empty interface and relying upon casting seems to sacrifice the benefits of typing

**Comment by jkelvie** [comment]
Hi @michaelgriscom - it's a good point. We wrote the library in typescript, but have primarily used it in JS, and have optimized for that (due to the fact that though we like TS, most of our users are on JS). One implication of this decision - we have strived to not pollute the serialized JSON form of the object - thus we have two completely distinct subclasses of the core IResponse object, with no shared properties.

The two subclasses are SkillResponse and DelegatedDialogResponse. The DelegatedDialogResponse is what is returned when our internal dialog manager is used to service a skill request, and has a very different payload structure. We do not know which payload will be returned until the call is made - at that point, we check the state of the interactions and the interaction model to determine if our internal dialog manager will handle the request or the skill will be called.

Given this, I don't believe a template parameter would really solve the issue. If I understand the template parameters correctly, someone would have to make a call like this:
```
await const response = virtualAlexa.intend<SkillResponse>("MyIntent")
```

Which just seems to be another form of casting without any additional type safety. Or am I missing something? I do have some additional thoughts on this, as I agree that there is some design smell here, but will pause here to make sure I am understanding what you have proposed correctly.

**Comment by michaelgriscom** [comment]
I see your point, it might be difficult to handle the polymorphism neatly without polluting the JSON form like you say. I was thinking that there may be either somewhere inside the interactors that can be made into a generic, but maybe you could treat it more compositionally, and let an IResponse have a SkillResponse inside it? Then the DelegatedDialogResponse would compose a SkillResponse with a prompt.

I haven't gotten the chance to look through the code architecture enough to offer a clear suggestion though, and it's a pretty small concern so feel free to close out this issue

**Comment by dgreene1** [comment]
> We wrote the library in typescript, but have primarily used it in JS, and have optimized for that (due to the fact that though we like TS, most of our users are on JS).
Count us as one more enthusiastic team of TypeScript users. My team and I are using Bespoken in TypeScript and would very much like a way to determine the type of IResponse that is coming back.

So @jkelvie, I implemented a potential solution that acknowledges that the type of response that comes back is more of a runtime problem than a compile time problem. Therefore, I've utilized type guards since I believe they are TypeScript's idiomatic way of guaranteeing type safety at runtime. Either way, type guards are generally more accurate (if written well (and I have unit tests)) than using the `as` keyword.

I love what you and your team are doing with Bespoken and I hope that you accept my first public PR! :)
https://github.com/bespoken/virtual-alexa/pull/96

**Comment by jkelvie** [comment]
Hi all, we have released a new version of virtual-alexa, version 0.7.1, that greatly simplifies this. We now have a single response class, [SkillResponse](https://bespoken.github.io/virtual-alexa/api/classes/skillresponse.html) that is returned by all the calls. This is similar to the discussion we have around your PR @dgreene1.

I hope you find this new version more intuitive to use.
